ktor {
    application {
        modules = [ fhirextinguisher.RestRouterKt.application ]
    }
}

FhirExtinguisher {
    fhirServerUrl = "http://hapi.fhir.org/baseR4"
    fhirVersion = "r4"
    // authorization = "username:password"
    queryStorage = "queryStorage.csv"
}