name: Publish Transform-FHIR Module

on:
  push:
    branches:
      - main
      - extinguisher-module
  workflow_dispatch:

jobs:
  publish:
    name: Publish Transform-FHIR Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Publish transform-fhir module
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :transform-fhir:publish